name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.6, 1.8]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: azure/login@v1.1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Generate UUID
        id: uuid
        run: julia -e 'using Random; write(stdout,"::set-output name=uuid::"*lowercase(randstring(21)))'
        shell: bash
      - name: Run Az CLI script
        run: |
          az group create -l southcentralus -n "AzureBackupRG-azstorage-${{ matrix.os }}-${{ matrix.julia-version }}-${{ github.run_id }}"
          az storage account create -n "s${{ steps.uuid.outputs.uuid }}" -g "AzureBackupRG-azstorage-${{ matrix.os }}-${{ matrix.julia-version }}-${{ github.run_id }}" -l southcentralus
      - uses: julia-actions/julia-buildpkg@latest #change lastest to master
      - uses: julia-actions/julia-runtest@latest #change lastest to master
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT: ${{ secrets.TENANT_ID }}
          STORAGE_ACCOUNT: "s${{ steps.uuid.outputs.uuid }}"
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
      - name: Run Az CLI script
        run: |
          az group delete -n "AzureBackupRG-azstorage-${{ matrix.os }}-${{ matrix.julia-version }}-${{ github.run_id }}" --yes
        if: ${{ always() }}
